name: buzsaki_tingley_long_term
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python==3.9
- pip
- git
- pip:
  - -e .
  - -r buzsaki_lab_to_nwb/tingley_long_term/tingley_long_term_requirements.txt
