name: CI development
on: [pull_request]
jobs:
  run:
    name: Development tests on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install this package, on development mode
      env:
          NWB_CONVERSION_INSTALL_MODE: development
      run: |
        pip install .
    - name: Run tests
      run: |
        pip install pytest
