name: Installation
on: push  # changing to schedule once confirmed working

jobs:
  run:
    name: Lazy tests on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install .
