name: Installation
on: pull_request

jobs:
  run:
    name: Installation on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e buzsaki_lab_to_nwb
    - name: Test module load
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import buzsaki_lab_to_nwb
