name: buzsaki-lab-to-nwb-env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - decorator=5.1.0
  - intel-openmp=2021.4.0
  - ipython=7.29.0
  - jedi=0.18.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - readline=8.1.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - asciitree==0.3.3
    - attrs==21.4.0
    - fasteners==0.16.3
    - h5py==3.6.0
    - hdf5storage==0.1.18
    - hdmf==3.1.1
    - joblib==1.1.0
    - jsonschema==3.2.0
    - lazy-ops==0.2.0
    - lxml==4.7.1
    - mat4py==0.5.0
    - mat73==0.52
    - natsort==8.0.2
    - neo==0.10.0
    - numcodecs==0.9.1
    - probeinterface==0.2.6
    - psutil==5.9.0
    - pynwb==2.0.0
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - quantities==0.13.0
    - roiextractors==0.3.1
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - spikeinterface==0.92.1.dev0
    - tqdm==4.62.3
    - zarr==2.10.3